name: CI

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: windows-2025
    strategy:
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Need at least 2 commits to properly gather changed files for linting
          fetch-depth: 2
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Install test dependencies
        run: |
          if (-not (Get-PSRepository -Name PSGallery -ErrorAction SilentlyContinue)) {
              Register-PSRepository -Default
          }
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module BuildHelpers, Pester -Scope CurrentUser -Force -SkipPublisherCheck
      - name: Run tests
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
